### ISSUE TITLE
meson 0.59.x uses `python3/dist-packages` on Ubuntu

### ISSUE THREAD

**Issue by ev-br** [ev-br/mc_lib#45]
In a local build on ubuntu focal, meson 

- reports a `WARNING: Broken python installation detected.`
- installs stuff into `installdir/python3/dist-packages` instead of `installdir/python3.8/site-packages`.

`pip install` with PEP517 + export PYTHONPATH works fine. On the CI, the install is still into `site-packages` (e.g. https://github.com/ev-br/mc_lib/runs/3847128334, which is a CI run of https://github.com/ev-br/mc_lib/pull/44).

Same behavior with meson 0.59.2 (the last release) and 0.59.99 (master branch as of 09 Oct 2021).

This was not observed in July/August 2021, and *probably* was not observed with meson 0.58.x --- so it's something new with virtualenv and meson 0.59.x. 

@rgommers this is what I mentioned offline

Full log: 

```
(mc_lib_2) br@gonzales:~/sweethome/proj/mc_lib$ meson setup builddir --prefix=$PWD/installdir
The Meson build system
Version: 0.59.99
Source dir: /home/br/sweethome/proj/mc_lib
Build dir: /home/br/sweethome/proj/mc_lib/builddir
Build type: native build
Project name: mc_lib
Project version: 0.3
C++ compiler for the host machine: c++ (gcc 9.3.0 "c++ (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0")
C++ linker for the host machine: c++ ld.bfd 2.34
Cython compiler for the host machine: cython (cython 0.29.24)
Host machine cpu family: x86_64
Host machine cpu: x86_64
Program cython found: YES (/home/br/.virtualenvs/mc_lib_2/bin/cython)
Program python3 found: YES (/home/br/.virtualenvs/mc_lib_2/bin/python)
WARNING: Broken python installation detected. Python files installed by Meson might not be found by python interpreter.
 This warning can be avoided by setting "python.platlibdir" option.
WARNING: Broken python installation detected. Python files installed by Meson might not be found by python interpreter.
 This warning can be avoided by setting "python.purelibdir" option.
Found pkg-config: /usr/bin/pkg-config (0.29.1)
Build targets in project: 6

mc_lib 0.3

  User defined options
    prefix: /home/br/sweethome/proj/mc_lib/installdir

Found ninja-1.10.2.git.kitware.jobserver-1 at /home/br/.virtualenvs/mc_lib_2/bin/ninja
(mc_lib_2) br@gonzales:~/sweethome/proj/mc_lib$ meson install -C builddir
ninja: Entering directory `/home/br/sweethome/proj/mc_lib/builddir'
[6/9] Compiling C++ object mc_lib/rndm.cpy...nux-gnu.so.p/meson-generated_.._rndm.cpp.o
In file included from /home/br/.virtualenvs/mc_lib_2/lib/python3.8/site-packages/numpy/core/include/numpy/ndarraytypes.h:1969,
                 from /home/br/.virtualenvs/mc_lib_2/lib/python3.8/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                 from /home/br/.virtualenvs/mc_lib_2/lib/python3.8/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from mc_lib/rndm.cpp:634:
/home/br/.virtualenvs/mc_lib_2/lib/python3.8/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning is a GCC extension
   17 | #warning "Using deprecated NumPy API, disable it with " \
      |  ^~~~~~~
/home/br/.virtualenvs/mc_lib_2/lib/python3.8/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
[8/9] Compiling C++ object mc_lib/tests/__...so.p/meson-generated_..___check_rndm.cpp.o
In file included from /home/br/.virtualenvs/mc_lib_2/lib/python3.8/site-packages/numpy/core/include/numpy/ndarraytypes.h:1969,
                 from /home/br/.virtualenvs/mc_lib_2/lib/python3.8/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                 from /home/br/.virtualenvs/mc_lib_2/lib/python3.8/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from mc_lib/tests/__check_rndm.cpp:634:
/home/br/.virtualenvs/mc_lib_2/lib/python3.8/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning is a GCC extension
   17 | #warning "Using deprecated NumPy API, disable it with " \
      |  ^~~~~~~
/home/br/.virtualenvs/mc_lib_2/lib/python3.8/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
[9/9] Linking target mc_lib/tests/__check_rndm.cpython-38-x86_64-linux-gnu.so
Installing mc_lib/rndm.cpython-38-x86_64-linux-gnu.so to /home/br/sweethome/proj/mc_lib/installdir/lib/python3/dist-packages/mc_lib
Installing mc_lib/observable.cpython-38-x86_64-linux-gnu.so to /home/br/sweethome/proj/mc_lib/installdir/lib/python3/dist-packages/mc_lib
Installing mc_lib/tests/__check_rndm.cpython-38-x86_64-linux-gnu.so to /home/br/sweethome/proj/mc_lib/installdir/lib/python3/dist-packages/mc_lib/tests
Installing /home/br/sweethome/proj/mc_lib/mc_lib/__init__.py to /home/br/sweethome/proj/mc_lib/installdir/lib/python3/dist-packages/mc_lib
Installing /home/br/sweethome/proj/mc_lib/mc_lib/rndm.pxd to /home/br/sweethome/proj/mc_lib/installdir/lib/python3/dist-packages/mc_lib
Installing /home/br/sweethome/proj/mc_lib/mc_lib/observable.pxd to /home/br/sweethome/proj/mc_lib/installdir/lib/python3/dist-packages/mc_lib
Installing /home/br/sweethome/proj/mc_lib/mc_lib/lattices/__init__.py to /home/br/sweethome/proj/mc_lib/installdir/lib/python3/dist-packages/mc_lib/lattices
Installing /home/br/sweethome/proj/mc_lib/mc_lib/lattices/_common.py to /home/br/sweethome/proj/mc_lib/installdir/lib/python3/dist-packages/mc_lib/lattices
Installing /home/br/sweethome/proj/mc_lib/mc_lib/lattices/_cubic.py to /home/br/sweethome/proj/mc_lib/installdir/lib/python3/dist-packages/mc_lib/lattices
Installing /home/br/sweethome/proj/mc_lib/mc_lib/lattices/_triang.py to /home/br/sweethome/proj/mc_lib/installdir/lib/python3/dist-packages/mc_lib/lattices
Installing /home/br/sweethome/proj/mc_lib/mc_lib/_observable/observable.h to /home/br/sweethome/proj/mc_lib/installdir/lib/python3/dist-packages/mc_lib/_observable
Installing /home/br/sweethome/proj/mc_lib/mc_lib/tests/__init__.py to /home/br/sweethome/proj/mc_lib/installdir/lib/python3/dist-packages/mc_lib/tests
Installing /home/br/sweethome/proj/mc_lib/mc_lib/tests/test_cubic_lattice.py to /home/br/sweethome/proj/mc_lib/installdir/lib/python3/dist-packages/mc_lib/tests
Installing /home/br/sweethome/proj/mc_lib/mc_lib/tests/test_observable.py to /home/br/sweethome/proj/mc_lib/installdir/lib/python3/dist-packages/mc_lib/tests
Installing /home/br/sweethome/proj/mc_lib/mc_lib/tests/test_rndm.py to /home/br/sweethome/proj/mc_lib/installdir/lib/python3/dist-packages/mc_lib/tests
Failed to apply ldconfig ...
Standard output:

Standard error:
/sbin/ldconfig.real: Can't create temporary cache file /etc/ld.so.cache~: Permission denied
```

**Comment by FFY00** [comment]
It's not a regression, as my patch hasn't been released yet.

https://github.com/mesonbuild/meson/commit/05b5a1e56fe8f5400b65d0d69680cc6531fe74f8

But my patch does not take virtual environments into account, only Python interpreters that are not patch by Debian when running on Debian-like systems. Fixing this should not be very hard, I will look at it tomorrow.

Slightly relevant Python bug: https://bugs.python.org/issue45413

**Comment by eli-schwartz** [comment]
> This was not observed in July/August 2021, and _probably_ was not observed with meson 0.58.x --- so it's something new with virtualenv and meson 0.59.x.

I suspect it was, in fact, silently broken the entire time ;)

meson now:
- reports a warning while detecting that the paths it used are not on sys.path, see https://github.com/mesonbuild/meson/commit/0063eb251e836e777b427cbe59b43ab937ac1924
- attempts to guess a better path than `get_option('prefix') / 'lib/python{ver}/site-packages'`, using an algorithm that changed several times during this development lifecycle
- finally, offers an option `-Dpython.platlibdir=` which allows you to set your own *absolute path* which will be respected utterly, and silence any warnings

We may in the future figure out a better way of supporting virtual environments directly. The current solution should be a pure upgrade from the previous status quo that only ever worked on non-Debian, non-Windows operating systems + installing to /usr.

**Comment by ev-br** [comment]
It might have been slightly broken, no idea from a user perspective. The current behavior is not very convenient, I'd also much prefer to have stable paths. 
The `-Dpython.platlibdir=` workaround seems to do something, but I'm neither sure what it does nor how to use it properly. 
My only guess is to give it `which python`, but this clearly not the right thing:

```
(mc_lib_2) br@gonzales:~/sweethome/proj/mc_lib$ meson setup builddir --prefix=$WD/installdir -Dpython.platlibdir=`which python`
The Meson build system Version: 0.59.99
Source dir: /home/br/sweethome/proj/mc_lib
Build dir: /home/br/sweethome/proj/mc_lib/builddir
Build type: native build
Project name: mc_lib
Project version: 0.3
C++ compiler for the host machine: c++ (gcc 9.3.0 "c++ (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0")
C++ linker for the host machine: c++ ld.bfd 2.34
Cython compiler for the host machine: cython (cython 0.29.24)
Host machine cpu family: x86_64
Host machine cpu: x86_64
Program cython found: YES (/home/br/.virtualenvs/mc_lib_2/bin/cython)
Program python3 found: YES (/home/br/.virtualenvs/mc_lib_2/bin/python)
WARNING: Broken python installation detected. Python files installed by Meson might not be found by python interpreter.
 This warning can be avoided by setting "python.purelibdir" option.
Found pkg-config: /usr/bin/pkg-config (0.29.1)
Build targets in project: 6

mc_lib 0.3

  User defined options
    prefix           : /installdir
    python.platlibdir: /home/br/.virtualenvs/mc_lib_2/bin/python

Found ninja-1.10.2.git.kitware.jobserver-1 at /home/br/.virtualenvs/mc_lib_2/bin/ninja
(mc_lib_2) br@gonzales:~/sweethome/proj/mc_lib$ which python
/home/br/.virtualenvs/mc_lib_2/bin/python
(mc_lib_2) br@gonzales:~/sweethome/proj/mc_lib$ meson install -C builddir
ninja: Entering directory `/home/br/sweethome/proj/mc_lib/builddir'
[6/9] Compiling C++ object mc_lib/rndm.cpython-38-x86_64-linux-gnu.so.p/meson-generated_.._rndm.cpp.o
In file included from /home/br/.virtualenvs/mc_lib_2/lib/python3.8/site-packages/numpy/core/include/numpy/ndarraytypes.h:1969,
                 from /home/br/.virtualenvs/mc_lib_2/lib/python3.8/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                 from /home/br/.virtualenvs/mc_lib_2/lib/python3.8/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from mc_lib/rndm.cpp:634:
/home/br/.virtualenvs/mc_lib_2/lib/python3.8/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning is a GCC extension
   17 | #warning "Using deprecated NumPy API, disable it with " \
      |  ^~~~~~~
/home/br/.virtualenvs/mc_lib_2/lib/python3.8/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
[8/9] Compiling C++ object mc_lib/tests/__check_rndm.cpython-38-x86_64-linux-gnu.so.p/meson-generated_..___check_rndm.cpp.o
In file included from /home/br/.virtualenvs/mc_lib_2/lib/python3.8/site-packages/numpy/core/include/numpy/ndarraytypes.h:1969,
                 from /home/br/.virtualenvs/mc_lib_2/lib/python3.8/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                 from /home/br/.virtualenvs/mc_lib_2/lib/python3.8/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from mc_lib/tests/__check_rndm.cpp:634:
/home/br/.virtualenvs/mc_lib_2/lib/python3.8/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning is a GCC extension
   17 | #warning "Using deprecated NumPy API, disable it with " \
      |  ^~~~~~~
/home/br/.virtualenvs/mc_lib_2/lib/python3.8/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
[9/9] Linking target mc_lib/tests/__check_rndm.cpython-38-x86_64-linux-gnu.so
Traceback (most recent call last):
  File "/home/br/.virtualenvs/mc_lib_2/lib/python3.8/site-packages/mesonbuild/mesonmain.py", line 228, in run
    return options.run_func(options)
  File "/home/br/.virtualenvs/mc_lib_2/lib/python3.8/site-packages/mesonbuild/minstall.py", line 754, in run
    installer.do_install(datafilename)
  File "/home/br/.virtualenvs/mc_lib_2/lib/python3.8/site-packages/mesonbuild/minstall.py", line 531, in do_install
    self.install_targets(d, dm, destdir, fullprefix)
  File "/home/br/.virtualenvs/mc_lib_2/lib/python3.8/site-packages/mesonbuild/minstall.py", line 663, in install_targets
    file_copied = self.do_copyfile(fname, outname, makedirs=(dm, outdir))
  File "/home/br/.virtualenvs/mc_lib_2/lib/python3.8/site-packages/mesonbuild/minstall.py", line 414, in do_copyfile
    dirmaker.makedirs(outdir, exist_ok=True)
  File "/home/br/.virtualenvs/mc_lib_2/lib/python3.8/site-packages/mesonbuild/minstall.py", line 105, in makedirs
    self.makedirs_impl(path, exist_ok=exist_ok)
  File "/home/br/.virtualenvs/mc_lib_2/lib/python3.8/site-packages/mesonbuild/minstall.py", line 316, in makedirs
    os.makedirs(*args, **kwargs)
  File "/usr/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
NotADirectoryError: [Errno 20] Not a directory: '/home/br/.virtualenvs/mc_lib_2/bin/python/mc_lib'
```

**Comment by FFY00** [comment]
IMO the warning should stay there as these are just heuristics, and could break if someone changes anything -- if Debian changes their patching, a Debian based distro tweaks some behavior, etc.

**Comment by ev-br** [comment]
OK, gave this another spin, now with `meson==0.60.3`. 
A funny thing is that when using `python.platlibdir` and `python.purelibdir`, `$ meson install -C build` ignores the `--prefix` and installs everything into the virtualenv's `site-packages` directory. Is this intended @eli-schwartz ?


```
$ meson setup build --prefix=$PWD/installdir -Dpython.platlibdir=/home/br/.virtualenvs/mc_lib_3/lib/python3.8/site-packages -Dpython.purelibdir=/home/br/.virtualenvs/mc_lib_3/lib/python3.8/site-packages
The Meson build system
Version: 0.60.3
Source dir: /home/br/sweethome/proj/mc_lib
Build dir: /home/br/sweethome/proj/mc_lib/build
Build type: native build
Project name: mc_lib
Project version: 0.3
C++ compiler for the host machine: c++ (gcc 9.3.0 "c++ (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0")
C++ linker for the host machine: c++ ld.bfd 2.34
Cython compiler for the host machine: cython (cython 0.29.26)
Host machine cpu family: x86_64
Host machine cpu: x86_64
Program cython found: YES (/home/br/.virtualenvs/mc_lib_3/bin/cython)
Program python3 found: YES (/home/br/.virtualenvs/mc_lib_3/bin/python)
Found pkg-config: /usr/bin/pkg-config (0.29.1)
Build targets in project: 6

mc_lib 0.3

  User defined options
    prefix           : /home/br/sweethome/proj/mc_lib/installdir
    python.platlibdir: /home/br/.virtualenvs/mc_lib_3/lib/python3.8/site-packages
    python.purelibdir: /home/br/.virtualenvs/mc_lib_3/lib/python3.8/site-packages

Found ninja-1.10.2.git.kitware.jobserver-1 at /home/br/.virtualenvs/mc_lib_3/bin/ninja
(mc_lib_3) br@gonzales:~/sweethome/proj/mc_lib$ 
(mc_lib_3) br@gonzales:~/sweethome/proj/mc_lib$ meson install -C build 
ninja: Entering directory `/home/br/sweethome/proj/mc_lib/build'
[9/9] Linking target mc_lib/tests/__check_rndm.cpython-38-x86_64-linux-gnu.so
Installing mc_lib/rndm.cpython-38-x86_64-linux-gnu.so to /home/br/.virtualenvs/mc_lib_3/lib/python3.8/site-packages/mc_lib
Installing mc_lib/observable.cpython-38-x86_64-linux-gnu.so to /home/br/.virtualenvs/mc_lib_3/lib/python3.8/site-packages/mc_lib
Installing mc_lib/tests/__check_rndm.cpython-38-x86_64-linux-gnu.so to /home/br/.virtualenvs/mc_lib_3/lib/python3.8/site-packages/mc_lib/tests
Installing /home/br/sweethome/proj/mc_lib/mc_lib/__init__.py to /home/br/.virtualenvs/mc_lib_3/lib/python3.8/site-packages/mc_lib
Installing /home/br/sweethome/proj/mc_lib/mc_lib/rndm.pxd to /home/br/.virtualenvs/mc_lib_3/lib/python3.8/site-packages/mc_lib
Installing /home/br/sweethome/proj/mc_lib/mc_lib/observable.pxd to /home/br/.virtualenvs/mc_lib_3/lib/python3.8/site-packages/mc_lib
Installing /home/br/sweethome/proj/mc_lib/mc_lib/lattices/__init__.py to /home/br/.virtualenvs/mc_lib_3/lib/python3.8/site-packages/mc_lib/lattices
Installing /home/br/sweethome/proj/mc_lib/mc_lib/lattices/_common.py to /home/br/.virtualenvs/mc_lib_3/lib/python3.8/site-packages/mc_lib/lattices
Installing /home/br/sweethome/proj/mc_lib/mc_lib/lattices/_cubic.py to /home/br/.virtualenvs/mc_lib_3/lib/python3.8/site-packages/mc_lib/lattices
Installing /home/br/sweethome/proj/mc_lib/mc_lib/lattices/_triang.py to /home/br/.virtualenvs/mc_lib_3/lib/python3.8/site-packages/mc_lib/lattices
Installing /home/br/sweethome/proj/mc_lib/mc_lib/_observable/observable.h to /home/br/.virtualenvs/mc_lib_3/lib/python3.8/site-packages/mc_lib/_observable
Installing /home/br/sweethome/proj/mc_lib/mc_lib/tests/__init__.py to /home/br/.virtualenvs/mc_lib_3/lib/python3.8/site-packages/mc_lib/tests
Installing /home/br/sweethome/proj/mc_lib/mc_lib/tests/test_cubic_lattice.py to /home/br/.virtualenvs/mc_lib_3/lib/python3.8/site-packages/mc_lib/tests
Installing /home/br/sweethome/proj/mc_lib/mc_lib/tests/test_observable.py to /home/br/.virtualenvs/mc_lib_3/lib/python3.8/site-packages/mc_lib/tests
Installing /home/br/sweethome/proj/mc_lib/mc_lib/tests/test_rndm.py to /home/br/.virtualenvs/mc_lib_3/lib/python3.8/site-packages/mc_lib/tests
(mc_lib_3) br@gonzales:~/sweethome/proj/mc_lib$ meson --version
0.60.3
```

**Comment by ev-br** [comment]
Looks like `meson==0.61.1` fixed the problem! The usual incantation (no platlibdir/purelib dir horror):
```
$ meson setup build --prefix=$PWD/installd
$ meson install -C build
```

produces

```
$ ll installd/lib/python3.8/
total 12
drwxr-xr-x 3 br br 4096 янв 30 21:28 ./
drwxr-xr-x 3 br br 4096 янв 30 21:28 ../
drwxr-xr-x 3 br br 4096 янв 30 21:28 site-packages/
```

This all in on the same setup as the OP : `virtualenv` (not stdlib venv!) on Ubuntu focal. gh-63 verifies it still works on CI, so closing.
